Add Floorp side Private Container implementation
nyanrus/noraneko pull request #12
Opened 2024-06-04 07:01 UTC by surapunoyousei

プライベートコンテナーの再提出

2024-06-04 11:53 UTC, nyanrus commented
inject要るとか言ってなかったっけ

2024-06-04 12:09 UTC, surapunoyousei commented
C 関係の改変が必要でまだやってない。んで Floorp Side なんよ

2024-06-04 15:33 UTC, surapunoyousei commented
いあらないことが発覚したのでコミット追加しておきます

2024-06-08 14:01 UTC, surapunoyousei commented
次こっちやらNight

2024-06-10 03:16 UTC, nyanrus requested changes
JS injectいるんじゃなかったっけ
inject追加されたらそん時に確認します

2024-06-10 03:17 UTC, surapunoyousei commented
時間かかると思う

2024-06-17 11:47 UTC, nyanrus commented
こっちのリファクタリングでそっちのリファクタのコミット要らなくなったっぽいしfixup って一つにまとめとってー

2024-06-17 11:48 UTC, surapunoyousei commented
REBASE しときます

2024-06-17 22:44 UTC, nyanrus approved these changes

2024-06-17 22:47 UTC, nyanrus commented
Thank you!

2024-06-17 22:47 UTC, merged