Implement revserse sidebar feature
nyanrus/noraneko pull request #16
Opened 2024-06-08 13:55 UTC by surapunoyousei

2024-06-11 08:37 UTC, nyanrus approved these changes
コンフリ解消よろ

2024-06-14 09:11 UTC, nyanrus requested changes

2024-06-14 09:11 UTC, nyanrus commented on src/content/browser/index.ts
> +    initUndoClosedTab();
undoclosedtab重複してますよ

2024-06-14 10:32 UTC, surapunoyousei commented on src/content/browser/index.ts
> +    initUndoClosedTab();
こりゃやっちまったねぇ！

2024-06-17 10:59 UTC, nyanrus approved these changes

2024-06-17 10:59 UTC, nyanrus commented
Thank you!

2024-06-17 11:02 UTC, nyanrus commented
@surapunoyousei GPG確認して

2024-06-17 13:38 UTC, surapunoyousei commented
署名した

2024-06-17 13:41 UTC, surapunoyousei commented
Rebase して全部のコミット一つにまとめて署名当てました

2024-06-17 22:43 UTC, merged