Tabbar のレイアウト関連
nyanrus/noraneko pull request #24
Opened 2024-07-06 08:26 UTC by surapunoyousei

垂直タブ、複数行のタブの実装もこっちに移す予定です。

デザインの実装を先にマージしないと動作しません

2024-08-05 15:09 UTC, Ryosuke-Asano commented
@nyanrus 動くようにはなった

2024-08-05 15:09 UTC, surapunoyousei commented
コンフリクト解消しとくね7

2024-08-10 06:45 UTC, nyanrus requested changes
PRありがとうございます。
修正をいくつかお願いします。

2024-08-10 06:45 UTC, nyanrus commented on apps/main/core/common/tabbar/tabbbar-style/tabbar-style-element.tsx
> +export function TabbarStyleModifyCSSElement(props: { style: string }) {
styleはzodのenumを使い回せると良いと思います。

2024-08-10 06:45 UTC, nyanrus commented on apps/main/core/common/tabbar/index.tsx
> +    import("./multirow-tabbar/multirow-tabbar")
importより、classの初期化をここでするようにする方がいいと思います。

2024-08-10 06:45 UTC, nyanrus commented on apps/main/core/common/tabbar/tabbbar-style/tabbbar-style-functions.tsx
> +class gTabbarStyleFunctionsClass {
constructorを使わないなら、namespaceをおすすめします。

2024-08-10 06:45 UTC, nyanrus commented on apps/main/core/common/tabbar/tabbbar-style/titilebar-padding.ts
> +export const checkPaddingEnabled = () => {
functionでお願いします。

2024-08-10 06:50 UTC, surapunoyousei commented
僕もなんかいろいろ気づいたから直すことにしますね。

2024-08-10 07:12 UTC, surapunoyousei commented on apps/main/core/common/tabbar/tabbbar-style/tabbar-style-element.tsx
> +export function TabbarStyleModifyCSSElement(props: { style: string }) {
修正した

2024-08-10 07:14 UTC, surapunoyousei commented on apps/main/core/common/tabbar/index.tsx
> +    import("./multirow-tabbar/multirow-tabbar")
export って関数内で使えるんだっけ

2024-08-10 07:27 UTC, nyanrus commented on apps/main/core/common/tabbar/index.tsx
> +    import("./multirow-tabbar/multirow-tabbar")
せっかくのgetInstanceなので
外でもgetInstanceを呼ぶようにしてください。

2024-08-10 15:22 UTC, surapunoyousei commented
終わり！

2024-08-11 03:26 UTC, nyanrus approved these changes
Thanks!

2024-08-11 03:27 UTC, nyanrus commented
@surapunoyousei 
署名お願いします。

2024-08-11 11:37 UTC, surapunoyousei commented
これでいいかな

2024-08-11 11:37 UTC, surapunoyousei commented
なんか上に二個あたってないのあるな。直す

2024-08-11 12:36 UTC, surapunoyousei commented
うーん、、、rebase のコンフリクト解決が地獄なので PR 作り直すわ。メールアドレスを大学に変更しろと言われて確認してなかったのが悪い

2024-08-11 12:36 UTC, closed without merging