Add browser-context-menu feature
nyanrus/noraneko pull request #4
Opened 2024-05-28 13:59 UTC by surapunoyousei

2024-05-28 23:04 UTC, nyanrus requested changes
Overall, seems good!

2024-05-28 23:04 UTC, nyanrus commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    window.setTimeout(() => {
Is there special meaning using setTimeout with 0?
if no, just use iife with async

2024-05-30 04:21 UTC, surapunoyousei commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    insert(document.body, xulElement, this.windowModalDialogElem);
![image](https://github.com/nyanrus/noraneko/assets/73892113/6f50c5e2-2c33-4398-a0a2-d79aa6a4e1e1)

JSX 要素を引数に与えるように強制しました。

2024-05-30 04:21 UTC, surapunoyousei commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    window.setTimeout(() => {
async() に変更ました。

2024-05-30 04:21 UTC, surapunoyousei commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    const contextMenu = ContextMenu(id, l10n, runFunction) as XULElement;
消しました

2024-05-30 04:27 UTC, nyanrus requested changes

2024-05-30 04:27 UTC, nyanrus commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    async () => {
This will not work because it is not called
find abt iife more

2024-05-30 04:29 UTC, surapunoyousei commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    async () => {
脳死で書いたら間違えた

2024-05-30 04:30 UTC, nyanrus commented
And you don't need rebase in reviewing

2024-05-30 04:42 UTC, surapunoyousei commented on src/content/browser/browser-context-menu/browser-context-menu.tsx
> +    async () => {
かえたお

2024-05-30 05:06 UTC, nyanrus approved these changes

2024-05-30 05:06 UTC, nyanrus commented
thx!

2024-05-30 05:06 UTC, merged