Implement SSB & Progressive Web App
nyanrus/noraneko pull request #87
Opened 2024-12-28 04:02 UTC by surapunoyousei

2025-01-04 14:18 UTC, nyanrus commented
@surapunoyousei 
起動後、"computations created outside a `createRoot` or `render` will never be disposed"や
"cleanups created outside a `createRoot` or `render` will never be run"などのログが出ていないことを確認してください。

2025-01-04 14:19 UTC, surapunoyousei commented
なるほど、確認します。

2025-01-04 18:00 UTC, surapunoyousei commented
多分うまくいった（警告は出てない）と思うのでレビューをお願いします。深夜に失礼しました。

2025-01-05 03:09 UTC, nyanrus requested changes
リクエストありがとうございます。
下記の変更要請をご確認ください。

2025-01-05 03:09 UTC, nyanrus commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
@noraComponentを使うと、createRootを少なく済ませることができます。
ご活用ください。

2025-01-05 06:00 UTC, surapunoyousei commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
pageActions は消すことができました。

2025-01-05 06:04 UTC, nyanrus commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
workspacesを参考に、getInstanceを無くせば、もっとコンパクトになります。
ご確認ください。
その他、createStoreも確認してみてください。
お読みいただきありがとうございます。

2025-01-05 13:57 UTC, nyanrus commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
@surapunoyousei ご確認お願いします。
通知が行ってないようですかね。

2025-01-05 13:58 UTC, surapunoyousei commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
おなかが下痢で死んでいます、

2025-01-06 13:01 UTC, surapunoyousei commented on src/apps/main/core/common/pwa/index.ts
> +export function init() {
PwaService という Class を定義して getInstance をほとんどないようにしました。

2025-01-06 14:41 UTC, merged